# -*- coding: utf-8 -*-
"""Enviroscan2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fF3CuoOIjLD6k_bOulQ1OLSnUmf_KLwa

Data Set in Loder
"""

import pandas as pd
import requests

def fetch_openap_data(city,params):
  url = f"https://api.openap.org/v2/measurements?city={city}"
  response = requests.get (url,params= params)
  data = response.json() ['results']
  return pd.DataFrame(data)

# data set of pollution
def fetch_weather_data(lat , lon , api_key):
    url = f"https://api.openweathermap.org/data/2.5/weather"
    params = {'lat': lat, 'lon': lon, 'appid': api_key}
    response = requests.get(url, params=params)
    return response.json()

#weather report
def get_location_features(lat, lon, dist=1000):
    G = ox.graph_from_point((lat, lon), dist=dist, network_type='drive')
    roads = ox.geometries.geometries_from_point((lat, lon), tags={'highway': True}, dist=dist)
    factories = ox.geometries.geometries_from_point((lat, lon), tags={'landuse': 'industrial'}, dist=dist)
    return {'roads': roads, 'factories': factories}

"""Data Cleaning and Feature Engineering"""

def clean_pollution_data(df):
    df = df.drop_duplicates()
    df = df.dropna(subset=['value', 'coordinates.latitude', 'coordinates.longitude'])
    df['value'] = pd.to_numeric(df['value'])
    df['timestamp'] = pd.to_datetime(df['date'])['utc']
    # Impute missing values
    df = df.fillna(df.mean())
    return df

def feature_engineering(df):
    # Normalize pollutant values
    for col in ['value']:
        df[col] = (df[col] - df[col].mean()) / df[col].std()

    # Calculate proximity features
    # Example: Calculate distance to nearest road
    # ... (implement with geopy or ox.distance.shortest_path)
    # Temporal features
    df['hour'] = df['timestamp'].dt.hour
    df['dayofweek'] = df['timestamp'].dt.dayofweek
    return df

"""Source Labelling and Simulation"""

def label_sources(df):
    # Example rules
    df['source'] = 'Unknown'

    df.loc[(df['near_main_road']==1) & (df['NO2'] > 40), 'source'] = 'Vehicular'
    df.loc[(df['near_factory']==1) & (df['SO2'] > 20), 'source'] = 'Industrial'
    df.loc[(df['near_farmland']==1) & (df['season']=='Dry') & (df['PM2.5']>70), 'source'] = 'Agricultural'

    # Simulate more labels if ground-truth missing
    # ...

    return df

"""Model Training and source prediction"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

def train_predict_model(df):
    features = ['PM2.5', 'NO2', 'SO2', 'CO', 'roads_proximity', 'factories_proximity', 'temperature', 'humidity', 'hour', 'dayofweek']
    X = df[features]
    y = df['source']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)
    clf = RandomForestClassifier()
    param_grid = {'n_estimators': [50, 100], 'max_depth': [5, 10, None]}
    grid = GridSearchCV(clf, param_grid)
    grid.fit(X_train, y_train)
    y_pred = grid.predict(X_test)

    print(classification_report(y_test, y_pred))

    return grid.best_estimator_

"""Geospatial Mapping and Visualisation"""

import folium

def plot_heatmap(df):
    m = folium.Map(location=[df['latitude'].mean(), df['longitude'].mean()], zoom_start=12)
    for _, row in df.iterrows():
        folium.Circle(
            location=[row['latitude'], row['longitude']],
            radius=50,
            color="red" if row['source'] == "Industrial" else "blue",
            fill=True
        ).add_to(m)
    return m

# m = plot_heatmap(labeled_df)

"""Real time dashboard and alerts (streamlit)"""

!pip install streamlit
!pip install pyngrok
!pip install -q streamlit pyngrok
import os

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.set_page_config(page_title="Pollution Source Identifier")
# 
# st.title(" 🤖 AI-Powered Pollution Source Identifier")
# 
# city = st.text_input("Enter a city name", placeholder="e.g., Delhi")
# 
# if st.button("Analyze"):
#     if city.strip() == "":
#         st.warning(" Please enter a valid city name.")
#     else:
#         st.success(f"Analyzing pollution sources for: {city}")
#         st.markdown(f"""
# ### AI Analysis Results for **{city}** (Simulated)
# - **Main Pollutants:** PM2.5, NOX, SO2
# - **Likely Sources:**
#   - Vehicle emissions
#   - Industrial activity
#   - Biomass/garbage burning
# - **Air Quality Index (AQI):** 185 (Unhealthy)
# - **Recommendation:** Limit outdoor activity. Use masks. Air purifiers recommended indoors.
# """)

# ✅ Step 1: Install required packages
!pip install pyngrok streamlit --quiet

# ✅ Step 2: Import necessary libraries
from pyngrok import ngrok
import time
import os
# ✅ Step 3: Export your ngrok authtoken (this sets an environment variable)
os.environ["NGROK_AUTHTOKEN"] = "32Q4NMHhzSBUduYMBv5Oyh54jg5_2toWjuF8icc3rJjCc9ZTr"

# ✅ Step 4: Authenticate pyngrok using the exported token
ngrok.set_auth_token(os.environ["NGROK_AUTHTOKEN"])

# ✅ Step 5: Kill any existing Streamlit process
!pkill streamlit

# ✅ Step 6: Define your Streamlit app code
app_code = '''
import streamlit as st

st.set_page_config(page_title="Streamlit via ngrok", page_icon="🎈")
st.title("🚀 Hello from Streamlit!")
st.write("This Streamlit app is running through an ngrok tunnel.")
'''

# ✅ Step 7: Write app code to a file
with open("app.py", "w") as f:
    f.write(app_code)

# ✅ Step 8: Start the Streamlit app in the background
!streamlit run app.py &> /content/logs.txt &

# ✅ Step 9: Wait a few seconds for the app to boot
time.sleep(15)

# ✅ Step 10: Open an ngrok tunnel to port 8501
public_url = ngrok.connect(8501)

# ✅ Step 11: Print the public URL
print("🌏 Your Streamlit app is live at:", public_url)

# Start Streamlit in background
!streamlit run app.py &> /content/logs.txt &

# Give more time for Streamlit to start (e.g., 15 seconds)
import time
time.sleep(15)

# Then create ngrok tunnel
from pyngrok import ngrok
public_url = ngrok.connect(8501)
print(" Your Streamlit app is live here:", public_url)

# Install required packages (run once)
!pip install --quiet streamlit pyngrok

import os
import time
import subprocess
from pyngrok import ngrok

# Set your ngrok auth token (replace with your actual token)
NGROK_AUTH_TOKEN = "32SqCst4NUzTNDrAlitGnP1d4eJ_6bRzhXot6qmzET4XCHbPz"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Write a simple Streamlit app
app_code = """
import streamlit as st

st.title("EnviroScan Pollution Source Identifier")

city = st.text_input("Enter a city name", "Delhi")
if st.button("Analyze"):
    if not city.strip():
        st.warning("Please enter a valid city name.")
    else:
        st.success(f"Analyzing pollution sources for: {city}")
        st.markdown(f'''
        ### AI Analysis Results for **{city}** (Simulated)
        - **Main Pollutants:** PM2.5, NOx, SO2
        - **Likely Sources:**
          - Vehicle emissions
          - Industrial activity
          - Biomass/garbage burning
        - **Air Quality Index (AQI):** 185 (Unhealthy)
        - **Recommendation:** Limit outdoor activity. Use masks. Air purifiers recommended indoors.
        ''')
"""

with open("app.py", "w") as f:
    f.write(app_code)

# Kill previous Streamlit instances cleanly
subprocess.run(["pkill", "-f", "streamlit"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

# Disconnect any existing ngrok tunnels to avoid free-tier limits
for tunnel in ngrok.get_tunnels():
    ngrok.disconnect(tunnel.public_url)

# Start Streamlit app in the background asynchronously
streamlit_process = subprocess.Popen(["streamlit", "run", "app.py"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

# Wait for the Streamlit server to start by checking logs
timeout = 30  # seconds
start_time = time.time()
server_started = False

while time.time() - start_time < timeout:
    line = streamlit_process.stdout.readline()
    if line:
        decoded_line = line.decode('utf-8')
        if "Network URL" in decoded_line or "Local URL" in decoded_line:
            server_started = True
            break
    else:
        time.sleep(1)

if not server_started:
    print("Warning: Streamlit server did not start within timeout.")

# Open ngrok tunnel on port 8501
public_url = ngrok.connect(8501)
print(f"Your Streamlit app is live at: {public_url}")

# Keep process alive to maintain server and tunnel
try:
    streamlit_process.wait()
except KeyboardInterrupt:
    print("Interrupted. Terminating Streamlit and ngrok tunnel...")
    streamlit_process.terminate()
    ngrok.disconnect(public_url)
    print("Terminated successfully.")

#  Install dependencies (run only once per environment)
!pip install --quiet streamlit pyngrok

import os
import time
import subprocess
import logging
from pyngrok import ngrok

#  Suppress ngrok warnings (optional)
logging.getLogger("pyngrok").setLevel(logging.ERROR)

#  Set ngrok auth token
NGROK_AUTH_TOKEN = "32SqCst4NUzTNDrAlitGnP1d4eJ_6bRzhXot6qmzET4XCHbPz"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

#  Define your Streamlit app code
app_code = """
import streamlit as st

st.set_page_config(page_title="EnviroScan", page_icon="")
st.title(" EnviroScan Pollution Source Identifier")

city = st.text_input("Enter a city name", "Delhi")

if st.button("Analyze"):
    if not city.strip():
        st.warning("Please enter a valid city name.")
    else:
        st.success(f"Analyzing pollution sources for: {city}")
        st.markdown(f'''
        ### AI Analysis Results for **{city}** (Simulated)
        - **Main Pollutants:** PM2.5, NOx, SO2
        - **Likely Sources:**
          - Vehicle emissions
          - Industrial activity
          - Biomass/garbage burning
        - **Air Quality Index (AQI):** 185 (Unhealthy)
        - **Recommendation:** Limit outdoor activity. Use masks. Air purifiers recommended indoors.
        ''')
"""

#  Save the app to a file
with open("app.py", "w") as f:
    f.write(app_code)

#  Kill existing Streamlit processes (clean start)
subprocess.run(["pkill", "-f", "streamlit"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

#  Disconnect any open ngrok tunnels
for tunnel in ngrok.get_tunnels():
    ngrok.disconnect(tunnel.public_url)

#  Start Streamlit app in background
streamlit_process = subprocess.Popen(["streamlit", "run", "app.py"])

#  Wait for Streamlit server to start
time.sleep(10)  # Increase if needed

#  Open ngrok tunnel to port 8501
public_url = ngrok.connect(8501)
print(f" Your Streamlit app is live at: {public_url}")

#  Keep the process alive
try:
    streamlit_process.wait()
except KeyboardInterrupt:
    streamlit_process.terminate()
    ngrok.disconnect(public_url)
    print("Streamlit and ngrok tunnel terminated.")

#  Install required packages
!pip install --quiet streamlit pyngrok requests
!pip install pyngrok

import os
import time
import subprocess
import logging
import requests
from pyngrok import ngrok

#  Silence noisy ngrok logs
logging.getLogger("pyngrok").setLevel(logging.ERROR)

#  Set your ngrok auth token
NGROK_AUTH_TOKEN = "32SqCst4NUzTNDrAlitGnP1d4eJ_6bRzhXot6qmzET4XCHbPz"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

#  Define your Streamlit app code
app_code = """
import streamlit as st

st.set_page_config(page_title="EnviroScan", page_icon="")
st.title(" EnviroScan Pollution Source Identifier")

city = st.text_input("Enter a city name", "Delhi")

if st.button("Analyze"):
    if not city.strip():
        st.warning("Please enter a valid city name.")
    else:
        st.success(f"Analyzing pollution sources for: {city}")
        st.markdown(f'''
        ### AI Analysis Results for **{city}** (Simulated)
        - **Main Pollutants:** PM2.5, NOx, SO2
        - **Likely Sources:**
          - Vehicle emissions
          - Industrial activity
          - Biomass/garbage burning
        - **Air Quality Index (AQI):** 185 (Unhealthy)
        - **Recommendation:** Limit outdoor activity. Use masks. Air purifiers recommended indoors.
        ''')
"""

#  Save Streamlit app
with open("app.py", "w") as f:
    f.write(app_code)

#  Kill any old Streamlit processes
subprocess.run(["pkill", "-f", "streamlit"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

#  Disconnect existing ngrok tunnels
for tunnel in ngrok.get_tunnels():
    ngrok.disconnect(tunnel.public_url)

#  Start Streamlit app in the background
streamlit_process = subprocess.Popen(["streamlit", "run", "app.py"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

#  Wait until the Streamlit app is actually up
def wait_for_streamlit(url="http://localhost:8501", timeout=30):
    for _ in range(timeout):
        try:
            r = requests.get(url)
            if r.status_code == 200:
                return True
        except:
            pass
        time.sleep(1)
    return False

if not wait_for_streamlit():
    streamlit_process.terminate()
    raise RuntimeError(" Streamlit did not start within 30 seconds.")

# ✅ Open ngrok tunnel
public_url = ngrok.connect(8501)
print(f"\n Your Streamlit app is live at: {public_url}\n")

# ✅ Keep it alive
try:
    streamlit_process.wait()
except KeyboardInterrupt:
    streamlit_process.terminate()
    ngrok.disconnect(public_url)
    print(" Terminated Streamlit and ngrok tunnel.")

!pip install osmnx

"""✅ Option 1: Use Streamlit Community Cloud (Free Hosting)

You can host your app on the internet without any local setup:

🔧 Steps:

Go to https://streamlit.io/cloud

Click “Sign in with GitHub”

Upload your app.py to a GitHub repo

Click “New App”

Choose the repo and file, and click “Deploy”

💡 Your app will be hosted on a public URL like: https://your-username-your-repo.streamlit.app

Option 2: Use Replit

Super easy if you don’t want to use GitHub or Colab.

🔧 Steps:

New section
Go to https://replit.com

Create a new Python Repl

Paste your Streamlit app code

Add streamlit to the Replit packages

Create a .replit file with:

run = "streamlit run app.py --server.port=8080 --server.headless=true" Hit "Run" — Replit will show you a public link Therefore, http://localhost:8501 and ngrok tunnel won’t work, because there’s no server to connect to.
"""

# ===============================
# STEP 1: Install dependencies
# ===============================
!pip install streamlit pyngrok --quiet

# ===============================
# STEP 2: Import libraries
# ===============================
import os
from pyngrok import ngrok

# ===============================
# STEP 3: Write a sample Streamlit app
# (you can replace this with your own code)
# ===============================
app_code = """
import streamlit as st

st.title("Hello from Streamlit in Google Colab 👋")
st.write("This is running on Colab with ngrok tunnel 🚀")

name = st.text_input("Enter your name:")
if name:
    st.success(f"Welcome, {name}!")
"""
with open("app.py", "w") as f:
    f.write(app_code)

# ===============================
# STEP 4: Kill any previous ngrok tunnels
# ===============================
ngrok.kill()

# ===============================
# STEP 5: Start Streamlit app
# (run in the background)
# ===============================
!streamlit run app.py &>/dev/null &

# ===============================
# STEP 6: Create public URL with ngrok
# ===============================
public_url = ngrok.connect(8501)
print("Streamlit is live here:", public_url)